### PR TITLE
Update budget.ex

### PR DESCRIPTION
**Pull request by josevalim**
For discussion. :)

### CODE REVIEW

**Comment by caike** [comment]
❤️

**Comment by caike** [comment]
I couldn't find any benefit in using `Stream` over `Enum`. I ran some benchmarks and the results were very similar, even with 500k rows on the csv file. One thing that could make `Stream` win would be if we needed to print just the first row, for example. But even then, the `Enum.sort` [here](https://github.com/caike/budget-elixir/blob/master/lib/budget.ex#L44) would force the stream to run before picking the first row. Thoughts ?

**Comment by josevalim** [comment]
I would use Enum. I thought you were using Stream for teaching purposes. :) If not, use Enum because that's the simplest, upgrade to Stream if provided to be necessary.

**Comment by caike** [comment]
Awesome! Thank you so much for all the help, you rock 🤘

**Pull request merged**
